name: Test Self-hosted Runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  spin-up-runner:
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
      TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
      SUBNETS: ${{ secrets.VPC_SUBNETS }}
      SECURITY_GROUPS: ${{ secrets.SECURITY_GROUPS }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Spin up ECS Runner
        run: |
          NETWORK_CONFIG="{\"awsvpcConfiguration\":{\"subnets\":[${{ env.SUBNETS }}],\"securityGroups\":[${{ env.SECURITY_GROUPS }}],\"assignPublicIp\":\"DISABLED\"}}"
          aws ecs run-task \
            --cluster ${{ env.CLUSTER_NAME }} \
            --task-definition ${{ env.TASK_DEFINITION }} \
            --launch-type FARGATE \
            --network-configuration "$NETWORK_CONFIG"

      - name: Wait for runner to be available
        run: |
          echo "Waiting for runner to register..."
          sleep 30

  test-on-runner:
    needs: spin-up-runner
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Runner
        run: |
          echo "Hello from self-hosted runner!"
          echo "Running in AWS ECS Fargate"
          echo "Current directory: $(pwd)"
          echo "Runner environment:"
          env | grep -v -i "key\|token\|secret"